import type { Metadata } from "next";
import {
  Climate_Crisis,
  Geist_Mono,
  UnifrakturMaguntia,
} from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/header/NavbarComponent";
import CartButton from "@/components/ui/CartButton";
import { CartProvider } from "@/contexts/CartContext";
import { Toaster } from "sonner";

const climate = Climate_Crisis({
  variable: "--font-climate",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const uni = UnifrakturMaguntia({
  variable: "--font-uni",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistMono.variable} ${climate.variable} ${uni.variable} antialiased`}
      >
        <CartProvider>
          <CartButton />
          <NavbarComponent />
          {children}
          <Toaster
            position="bottom-right"
            richColors
            toastOptions={{
              style: {
                background: "#000000",
                color: "#a3e635",
                border: "2px solid #a3e635",
                borderRadius: "12px",
              },
              className: "font-mono",
            }}
          />{" "}
        </CartProvider>
      </body>
    </html>
  );
}
